services:
  nginx:
    image: nginx:stable
    restart: unless-stopped
    ports:
      - 67:80
    environment: {}
    depends_on:
      - nodejs-backend
    networks: &a1
      - app-network
  nodejs-backend:
    image: node:20-alpine
    restart: unless-stopped
    deploy:
      replicas: 2
    environment: {}
    depends_on:
      - postgres
    command:
      - tail
      - -f
      - /dev/null
    networks: *a1
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: abcabcabc
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U app
      interval: 10s
      timeout: 5s
      retries: 5
      startPeriod: 10s
    networks: *a1
networks:
  app-network: {}
volumes:
  postgres-data: {}
