services:
  nginx:
    image: nginx:stable
    restart: unless-stopped
    deploy:
      replicas: 1
    ports:
      - 80:80
    environment: {}
    depends_on:
      - api
    networks:
      - app-network
  api:
    image: node:20-alpine
    restart: unless-stopped
    deploy:
      replicas: 2
    environment: {}
    depends_on:
      - postgres-1
    command:
      - tail
      - -f
      - /dev/null
    networks:
      - app-network
  postgres-1:
    image: postgres:16
    restart: unless-stopped
    deploy:
      replicas: 1
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: abcabcabc
      POSTGRES_PASSWORD: pw-bf687965917e65b38f8817df
    volumes:
      - postgres-data-1:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U app
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - app-network
networks:
  app-network: {}
volumes:
  postgres-data-1: {}
