import type { InfrastructureSpec } from '../domain/types.js';

/**
 * Secret resolution layer (roadmap: "He thong quan ly Secret").
 *
 * The agent already injects temporary default secrets via `generateDefaultSecret()`
 * into the InfrastructureSpec. This module runs AFTER the agent returns and decides
 * the final value for every secret-like environment key, using the priority:
 *
 *   1. `.env` (process.env) — user-declared values win whenever present.
 *   2. auto-generated (the value already in the spec) — fallback when env is absent.
 *
 * No new fields are added to InfrastructureSpec; the resolver only rewrites
 * `service.environment` values for secret-like keys.
 */

const SECRET_KEY_PATTERN = /(PASSWORD|PASS|SECRET|TOKEN|KEY)$/i;
const USER_KEY_PATTERN = /(^|_)USER(NAME)?$/i;

export type SecretSource = 'env-file' | 'auto-generated';

export interface ResolvedSecret {
  /** Original environment variable name, e.g. "POSTGRES_PASSWORD". */
  key: string;
  /** Name used to look up process.env (prefixed when the same key is shared by 2+ services). */
  envVarName: string;
  /** Resolved real value. */
  value: string;
  source: SecretSource;
}

export interface ServiceSecretResolution {
  serviceName: string;
  secrets: ResolvedSecret[];
}

export interface SecretResolutionResult {
  services: ServiceSecretResolution[];
  /** Spec with resolved secret values substituted into service.environment. */
  updatedSpec: InfrastructureSpec;
}

/** Shared secret-key detector so CLI / policy / resolver do not duplicate the regex. */
export function isSecretLikeKey(key: string): boolean {
  return SECRET_KEY_PATTERN.test(key);
}

export interface ResolveSecretsOptions {
  /**
   * Environment to read `.env`-style values from. Defaults to `process.env`
   * (already loaded by the CLI via `process.loadEnvFile('.env')`).
   */
  env?: Record<string, string | undefined>;
}

export function resolveSecrets(
  spec: InfrastructureSpec,
  _previousSpec?: InfrastructureSpec | null,
  options: ResolveSecretsOptions = {},
): SecretResolutionResult {
  const env = options.env ?? process.env;

  // 1. Count environment keys across services to detect duplicates that can be prefixed.
  const environmentKeyCounts = new Map<string, number>();
  for (const service of spec.services) {
    for (const key of Object.keys(service.environment ?? {})) {
      if (isSecretLikeKey(key) || isUserLikeKey(key)) {
        environmentKeyCounts.set(key, (environmentKeyCounts.get(key) ?? 0) + 1);
      }
    }
  }

  const resolutions: ServiceSecretResolution[] = [];
  const updatedServices = spec.services.map((service) => {
    const secrets: ResolvedSecret[] = [];
    const updatedEnvironment = { ...(service.environment ?? {}) };

    for (const [key, currentValue] of Object.entries(service.environment ?? {})) {
      const isSecret = isSecretLikeKey(key);
      const isUser = isUserLikeKey(key);
      if (!isSecret && !isUser) {
        continue;
      }

      const isDuplicate = (environmentKeyCounts.get(key) ?? 0) > 1;

      let value = currentValue;
      let source: SecretSource = isSecret ? 'auto-generated' : 'env-file';
      let envVarName = key;

      // Priority 1: `.env` — user-declared values win whenever present.
      // Empty string counts as "not provided".
      const envValue = resolveEnvValue(env, key, service.name, isDuplicate);
      if (envValue !== null) {
        value = envValue.value;
        envVarName = envValue.envVarName;
        source = 'env-file';
      } else if (!isSecret) {
        source = 'auto-generated';
      }
      // Priority 2: keep the auto-generated value already in the spec.

      updatedEnvironment[key] = value;
      if (isSecret) {
        secrets.push({ key, envVarName, value, source });
      }
    }

    if (secrets.length > 0) {
      resolutions.push({ serviceName: service.name, secrets });
    }

    return { ...service, environment: updatedEnvironment };
  });

  return {
    services: resolutions,
    updatedSpec: { ...spec, services: updatedServices },
  };
}

/** True when at least one resolved secret came from the auto-generated fallback. */
export function hasAutoGeneratedSecrets(result: SecretResolutionResult): boolean {
  return result.services.some((service) =>
    service.secrets.some((secret) => secret.source === 'auto-generated'),
  );
}

function toEnvPrefix(serviceName: string): string {
  return serviceName.replace(/[^A-Za-z0-9]/g, '_').toUpperCase();
}

function isUserLikeKey(key: string): boolean {
  return USER_KEY_PATTERN.test(key);
}

function resolveEnvValue(
  env: Record<string, string | undefined>,
  key: string,
  serviceName: string,
  isDuplicate: boolean,
): { envVarName: string; value: string } | null {
  const envVarNames = isDuplicate ? [`${toEnvPrefix(serviceName)}_${key}`, key] : [key];
  for (const envVarName of envVarNames) {
    const value = env[envVarName];
    if (value !== undefined && value !== '') {
      return { envVarName, value };
    }
  }
  return null;
}
